apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-app
  namespace: staging-deployment
  labels:
    app: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - name: customer
        image: 353258999787.dkr.ecr.us-east-1.amazonaws.com/customer_service_microservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3333
          protocol: TCP
      - name: mongo
        image: library/mongo
        ports:
        - containerPort: 27017
          protocol: TCP     
---
apiVersion: v1
kind: Service
metadata:
  name: customer
  namespace: staging-deployment
  labels:
    app: customer
    service: customer
spec:
  ports:
    - name: port1
      protocol: TCP
      port: 3333
      targetPort: 3333
    - name: port2
      protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: customer
    type: nodeport
